apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: jp-server
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/kubernetes-manifest.new.yaml
profiles:
- name: dev
  build:
    local:
      push: false
  deploy:
    kubectl: {}
portForward:
  - resourceType: service
    resourceName: jp-server-service
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: postgres-service
    port: 5432
    localPort: 5432
